import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase-admin';
import crypto from 'crypto';

export async function POST(req: NextRequest) {
    try {
        const {
            razorpay_order_id,
            razorpay_payment_id,
            razorpay_signature,
            planId
        } = await req.json();

        // 1. Verify Signature
        // The signature is generated by hashing order_id|payment_id with the secret
        const secret = process.env.RP_KEY_SECRET;
        if (!secret) throw new Error('Server misconfigured: RP_KEY_SECRET missing');

        const body = razorpay_order_id + "|" + razorpay_payment_id;
        const expectedSignature = crypto
            .createHmac('sha256', secret)
            .update(body.toString())
            .digest('hex');

        console.log('[Verify] Debug:', {
            received: razorpay_signature,
            calculated: expectedSignature,
            match: expectedSignature === razorpay_signature,
            oid: razorpay_order_id,
            pid: razorpay_payment_id
        });

        const isSignatureValid = expectedSignature === razorpay_signature;

        if (!isSignatureValid) {
            console.error('[Verify] Signature Mismatch');
            return NextResponse.json({ error: 'Invalid Payment Signature' }, { status: 400 });
        }

        // 2. Identify User from Order?
        // Ideally we stored the order_id -> user_id mapping in a DB or passed it securely.
        // For this implementation, we will fetch the order from Razorpay to get the "notes.userId"
        // OR rely on the client passing userId (insecure).
        // BETTER: Retrieve user from session context if authenticated.

        // Wait, for verification we generally want to rely on server-side stored state or signed data.
        // But since we put userId in "notes" on the order, we can trust it IF we fetch the order from Razorpay.
        // However, fetching from razorpay adds latency. 
        // A simpler way for MVP: Just update the user passed in the session context (cookie).

        // We'll use our secure `getOrCreateUser` helper if this was a protected route, 
        // BUT verify happens after payment, maybe via webhook? 
        // If this is called from Client `handler` function, user is logged in.

        // Let's assume client call for now (easiest integration).
        const { getOrCreateUser } = await import('@/lib/user-sync');
        const userId = await getOrCreateUser();

        if (!userId) {
            // Fallback: If session lost, we rely on the order's notes (fetching from RP is safest then)
            // But let's assume session is active for the immediate callback.
            return NextResponse.json({ error: 'User session not found during verification' }, { status: 401 });
        }

        // 3. Update Database using admin client
        // Create or Update subscription
        const { error } = await supabaseAdmin
            .from('users')
            .update({
                subscription_status: 'active',
                subscription_plan: planId || 'pro_monthly',
                subscription_id: razorpay_order_id // storing order_id as sub ref for now
            })
            .eq('id', userId);

        if (error) {
            console.error('DB Update Failed:', error);
            // Valid payment but DB failed - log critical error
            return NextResponse.json({ error: 'Payment verified but DB update failed' }, { status: 500 });
        }

        return NextResponse.json({ success: true });

    } catch (error: any) {
        console.error('Razorpay Verify Error:', error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
